import {TimerEngine} from "./timer-engine.js";import {DeskStage} from "./desk-stage.js";import {SoundManager} from "./sound-manager.js";import {StatsStorage} from "./stats-storage.js";import {inventory} from "./inventory-state.js";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],storage=new StatsStorage(),sound=new SoundManager();let state=storage.load(),catalog="items",lastClink=null;
const stage=new DeskStage($("#deskCard"),$("#cat"),$("#pushItem"));
const timer=new TimerEngine(renderTimer,completeSession);
function format(n){return `${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`}
function renderTimer(s){$("#timeDisplay").textContent=format(s.left);$("#progressFill").style.width=`${s.progress*100}%`;$("#statusText").textContent=s.mode==="short"?(s.running?"CATNAP IN PROGRESS":"CATNAP READY"):(s.running?"MENACE IN MOTION":"READY TO FOCUS");$("#startBtn").innerHTML=s.running?"<span>■</span> Focusing…":"<span>▶</span> Start focus";$("#nudgeText").textContent=s.mode==="short"?"The menace is recharging.":s.progress>.8?"Careful... one paw at a time.":"The glass is safe... for now.";stage.render(s);if(s.mode==="work"&&s.left<=120&&s.left>0&&s.left%10===0&&lastClink!==s.left){lastClink=s.left;sound.clink();navigator.vibrate?.(12)}}
function completeSession(s){if(s.mode==="work"){storage.complete(state,state.selected,Math.round(s.total/60));sound.can();toast("Item saved! +10 catnip coins");stage.card.classList.add("break");setTimeout(()=>switchMode("short"),1000)}else{sound.meow();toast("Catnap over. Back to the desk!");switchMode("work")}renderStats()}
function switchMode(mode){timer.switchMode(mode);$$('.mode-btn').forEach(b=>b.classList.toggle('active',b.dataset.mode===mode));}
function toast(text){$("#toast").textContent=text;$("#toast").classList.add("show");setTimeout(()=>$("#toast").classList.remove("show"),2200)}
$("#startBtn").onclick=()=>timer.running?null:timer.start();$("#pauseBtn").onclick=()=>{if(timer.running){timer.pause();sound.tone(480,.12);toast("Laser deployed. Menace distracted.")}else if(timer.left<timer.total)timer.start()};$("#abortBtn").onclick=()=>{if(timer.mode==="work"&&timer.left<timer.total){timer.pause();stage.crash();sound.crash();storage.recordBreakage(state);toast("CRASH! Another one for the broken pile.");setTimeout(()=>timer.reset(),700);renderStats()}else timer.reset()};$("#cat").onclick=()=>stage.poke(sound);$$('.mode-btn').forEach(b=>b.onclick=()=>switchMode(b.dataset.mode));
$$('.nav-btn').forEach(b=>b.onclick=()=>{$$('.nav-btn').forEach(x=>x.classList.toggle('active',x===b));$("#timerView").hidden=b.dataset.view!=="timer";$("#statsView").hidden=b.dataset.view!=="stats";if(b.dataset.view==="stats")renderStats()});
$("#scanlineToggle").onclick=e=>{state.settings.scanlines=!state.settings.scanlines;document.body.classList.toggle("scanlines-on",state.settings.scanlines);e.currentTarget.classList.toggle("active",state.settings.scanlines);storage.save(state)};$("#soundToggle").onclick=e=>{state.settings.ambient=!state.settings.ambient;sound.setAmbient(state.settings.ambient);e.currentTarget.classList.toggle("active",state.settings.ambient);storage.save(state);toast(state.settings.ambient?"Lo-fi purr mode on":"Lo-fi purr mode off")};document.body.classList.toggle("scanlines-on",state.settings.scanlines);$("#scanlineToggle").classList.toggle("active",state.settings.scanlines);
function renderStats(){$("#coinBalance").textContent=$("#coinsMetric").textContent=state.coins;$("#focusMetric").textContent=state.focusMinutes>=60?`${(state.focusMinutes/60).toFixed(1)}h`:`${state.focusMinutes}m`;$("#streakMetric").textContent=state.streak;$("#savedShelf").innerHTML=state.saved.length?state.saved.slice(-10).map(id=>`<span class="saved-item" title="${inventory.items.find(x=>x.id===id)?.name||id}">${inventory.items.find(x=>x.id===id)?.icon||"🏆"}</span>`).join(""):"Nothing saved yet.";$("#brokenPile").textContent=state.broken?`${"🏺 ".repeat(Math.min(state.broken,8))} ${state.broken} glorious accident${state.broken===1?"":"s"}`:"No casualties. Yet."}
function renderCatalog(){const owned=catalog==="items"?state.unlocked:state.cosmetics;$("#catalogGrid").innerHTML=inventory[catalog].map(x=>`<article class="catalog-card"><div class="art">${x.icon}</div><b>${x.name}</b><small>${x.price?`${x.price} catnip coins`:"Starter item"}</small><button data-buy="${x.id}" ${owned.includes(x.id)&&catalog==="cosmetics"?"disabled":""}>${catalog==="items"&&state.selected===x.id?"Equipped":owned.includes(x.id)?catalog==="items"?"Equip":"Owned":"Unlock"}</button></article>`).join("");$$('[data-buy]').forEach(b=>b.onclick=()=>buy(b.dataset.buy))}
function buy(id){const list=inventory[catalog],item=list.find(x=>x.id===id),owned=catalog==="items"?state.unlocked:state.cosmetics;if(owned.includes(id)){if(catalog==="items")state.selected=id;else state.equippedCosmetic=id}else if(state.coins>=item.price){state.coins-=item.price;owned.push(id);if(catalog==="items")state.selected=id;else state.equippedCosmetic=id;toast(`${item.name} unlocked!`)}else return toast("Not enough catnip coins");storage.save(state);renderStats();renderStageInventory();renderCatalog()}
$("#shopButton").onclick=()=>{$("#catalogModal").hidden=false;renderCatalog()};$$('[data-close]').forEach(b=>b.onclick=()=>$("#catalogModal").hidden=true);$$('[data-catalog]').forEach(b=>b.onclick=()=>{catalog=b.dataset.catalog;$$('[data-catalog]').forEach(x=>x.classList.toggle('active',x===b));renderCatalog()});function renderStageInventory(){const selected=inventory.items.find(item=>item.id===state.selected)||inventory.items[0];stage.item.className=`push-item item-${selected.id}`;stage.item.setAttribute("aria-label",selected.name);const cosmetic=inventory.cosmetics.find(item=>item.id===state.equippedCosmetic);$("#catCosmetic").textContent=cosmetic?.icon||"";$("#catCosmetic").dataset.cosmetic=cosmetic?.id||""}
document.addEventListener("keydown",e=>{if(e.key==="Escape")$("#catalogModal").hidden=true});renderStats();renderStageInventory();renderTimer(timer.snapshot());
